# Generated by Django 5.2 on 2025-07-20 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[('loyer', 'Loyer'), ('eau', 'Eau'), ('electricite', 'Électricité'), ('internet', 'Internet'), ('reparation', 'Réparation')], max_length=20)),
                ('mois_concerne', models.CharField(help_text='Ex: Juin 2025', max_length=20)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier_recu', models.FileField(blank=True, null=True, upload_to='reçus/')),
                ('locataire', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
