# Generated by Django 5.2 on 2025-07-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='proprietaire',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
