# Generated by Django 5.2.4 on 2025-07-31 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_property_images_imagelogement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to=settings.AUTH_USER_MODEL),
        ),
    ]
