# Generated by Django 5.2 on 2025-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_paiement',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Espèce', 'Espèce'), ('Virement', 'Virement')], default='Mobile Money', max_length=20),
        ),
    ]
